### **将 `arr`转换为2行的2维数组。**
- `arr = np.arange(10)`

【知识点：数组的操作】
- 如何改变数组的形状？

### **垂直堆叠数组a和数组b。**
- `a = np.arange(10).reshape([2, -1])`
- `b = np.repeat(1, 10).reshape([2, -1])`

【知识点：数组操作】
- 如何垂直叠加两个数组？

### 将数组a与数组b水平堆叠。
- `a = np.arange(10).reshape([2, -1])`
- `b = np.repeat(1, 10).reshape([2, -1])`

【知识点：数组的操作】
- 如何水平叠加两个数组？

### **将 `arr`的2维数组按列输出。**

- `arr =  np.array([[16, 17, 18, 19, 20],[11, 12, 13, 14, 15],[21, 22, 23, 24, 25],[31, 32, 33, 34, 35],[26, 27, 28, 29, 30]])`

【知识点：数组的操作】
- 如何访问二维数组的全部元素，并按列输出？

### **给定两个随机数组A和B，验证它们是否相等。**

- `A = np.random.randint(0,2,5) B = np.random.randint(0,2,5)`

【知识点：数组的操作】
- np.allclose()

### **在给定的numpy数组中找到重复的条目（第二次出现以后），并将它们标记为True。第一次出现应为False。**

- `a = np.random.randint(0, 5, 10)`

【知识点：数组操作】
- 如何在numpy数组中找到重复值？

In [1]:
import numpy as np

In [2]:
arr = np.arange(10)
print(arr.shape)
arr.shape = (2, 5)
print(arr)

(10,)
[[0 1 2 3 4]
 [5 6 7 8 9]]


In [3]:
a = np.arange(10).reshape([2, -1])
b = np.repeat(1, 10).reshape([2, -1])
print(a)
print(b)
arr = np.concatenate((a, b), axis=0)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4]
 [5 6 7 8 9]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [4]:
a = np.arange(10).reshape([2, -1])
b = np.repeat(1, 10).reshape([2, -1])
print(a)
print(b)
arr = np.concatenate((a, b), axis=1)
print(arr)

[[0 1 2 3 4]
 [5 6 7 8 9]]
[[1 1 1 1 1]
 [1 1 1 1 1]]
[[0 1 2 3 4 1 1 1 1 1]
 [5 6 7 8 9 1 1 1 1 1]]


In [5]:
arr =  np.array([
    [16, 17, 18, 19, 20],
    [11, 12, 13, 14, 15],
    [21, 22, 23, 24, 25],
    [31, 32, 33, 34, 35],
    [26, 27, 28, 29, 30]]
)
print(arr)
new_arr = arr.flatten(order='F')
print(new_arr)

[[16 17 18 19 20]
 [11 12 13 14 15]
 [21 22 23 24 25]
 [31 32 33 34 35]
 [26 27 28 29 30]]
[16 11 21 31 26 17 12 22 32 27 18 13 23 33 28 19 14 24 34 29 20 15 25 35
 30]


In [6]:
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)
np.allclose(A, B)

False

In [7]:
a = np.random.randint(0, 5, 10)
print(a)
u, indices = np.unique(a, return_index=True)
b = np.full(10, True)
b[indices] = False
print(b)

[1 2 0 3 3 1 0 1 2 4]
[False False False False  True  True  True  True  True False]
