### **什么是numpy？**


### **如何安装numpy？**

### **什么是n维数组对象？**

### **如何区分一维、二维、多维？**

### **以下表达式运行的结果分别是什么?**

(提示: NaN = not a number, inf = infinity)

0 * np.nan

np.nan == np.nan

np.inf > np.nan

np.nan - np.nan

0.3 == 3 * 0.1

### **将numpy的datetime64对象转换为datetime的datetime对象。**

- `dt64 = np.datetime64('2020-02-25 22:10:10')`

【知识点：时间日期和时间增量】
- 如何将numpy的datetime64对象转换为datetime的datetime对象？

### **给定一系列不连续的日期序列。填充缺失的日期，使其成为连续的日期序列。**

- `dates = np.arange('2020-02-01', '2020-02-10', 2, np.datetime64)`

【知识点：时间日期和时间增量、数学函数】
- 如何填写不规则系列的numpy日期中的缺失日期？

### **如何得到昨天，今天，明天的的日期**

【知识点：时间日期】
- (提示: np.datetime64, np.timedelta64)


### **创建从0到9的一维数字数组。**

【知识点：数组的创建】
- 如何创建一维数组？

### **创建一个元素全为`True`的 3×3 数组。**

【知识点：数组的创建】
- 如何创建一个布尔数组？

### **创建一个长度为10并且除了第五个值为1的空向量**

【知识点：数组的创建】

- (提示: array[4])

### **创建一个值域范围从10到49的向量**

【知识点：创建数组】

- (提示: np.arange)

### **创建一个 3x3x3的随机数组**

【知识点：创建数组】

(提示: np.random.random)

### **创建一个二维数组，其中边界值为1，其余值为0**

【知识点：二维数组的创建】

- (提示: array[1:-1, 1:-1])

### **创建长度为10的numpy数组，从5开始，在连续的数字之间的步长为3。**

【知识点：数组的创建与属性】
- 如何在给定起始点、长度和步骤的情况下创建一个numpy数组序列？

### **将本地图像导入并将其转换为numpy数组。**

【知识点：数组的创建与属性】
- 如何将图像转换为numpy数组？

In [1]:
import numpy as np

In [2]:
np.isnan(0 * np.nan)

True

In [3]:
np.nan == np.nan

False

In [4]:
np.inf > np.nan  # nan 无法比较大小

False

In [5]:
np.nan - np.nan  # nan 无法进行运算操作

nan

In [6]:
0.3 == 3 * 0.1  # 浮点型操作

False

In [7]:
import datetime
dt64 = np.datetime64('2020-02-25 22:10:10')
dt64.astype(datetime.datetime)

datetime.datetime(2020, 2, 25, 22, 10, 10)

In [8]:
dates = np.arange('2020-02-01', '2020-02-10', 2, np.datetime64)
print(dates)

['2020-02-01' '2020-02-03' '2020-02-05' '2020-02-07' '2020-02-09']


In [9]:
today = np.datetime64('today')
yesterday = today - np.timedelta64(1, 'D')
tomorrow = today + np.timedelta64(1, 'D')
yesterday, today, tomorrow

(numpy.datetime64('2020-10-19'),
 numpy.datetime64('2020-10-20'),
 numpy.datetime64('2020-10-21'))

In [10]:
d = np.arange(0, 10, 1, np.int_)
d

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
d = np.full((3, 3), True)
d

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [12]:
a = np.zeros(10, np.int_)
a[4] = 1
a

array([0, 0, 0, 0, 1, 0, 0, 0, 0, 0])

In [13]:
np.arange(10, 50, 1)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [14]:
rng = np.random.default_rng()
rng.random((3,3,3))

array([[[0.80965864, 0.01713236, 0.04901262],
        [0.68813733, 0.1090488 , 0.47906077],
        [0.5908615 , 0.1846797 , 0.84152309]],

       [[0.11354834, 0.5215204 , 0.95472011],
        [0.88393612, 0.95927358, 0.12187009],
        [0.49768631, 0.81578232, 0.85816353]],

       [[0.9130485 , 0.56282676, 0.85844373],
        [0.5267985 , 0.69092626, 0.23622324],
        [0.94328271, 0.15534502, 0.8815091 ]]])

In [15]:
x = np.ones((5, 5))
x[1:-1, 1:-1] = 0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
np.arange(5, 5 + 10 * 3, 3)

array([ 5,  8, 11, 14, 17, 20, 23, 26, 29, 32])

In [17]:
from PIL import Image
import requests
from io import BytesIO
response = requests.get('https://github.com/datawhalechina/team-learning-program/raw/master/IntroductionToNumpy/task01%20%E6%95%B0%E6%8D%AE%E7%B1%BB%E5%9E%8B%E5%8F%8A%E6%95%B0%E7%BB%84%E5%88%9B%E5%BB%BA/test.jpg')
img = Image.open(BytesIO(response.content))
i = np.array(img)
i.shape, i.dtype

((959, 959, 3), dtype('uint8'))